name: "headartist-texture-refine"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 42

data_type: "random-camera-datamodule"
data:
  batch_size: 1
  width: 512
  height: 512
  camera_distance_range: [3, 3]
  fovy_range: [30, 50]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  elevation_range: [-10, 45]
  azimuth_range: [-180, 180]
  batch_uniform_azimuth: true
  eval_camera_distance: 3.
  eval_fovy_deg: 45.


system_type: "headartist-system"
system:
  geometry_type: "tetrahedra-sdf-grid"
  stage: "texture"
  geometry_convert_from: ???
  geometry:
    radius: 1.0 # consistent with last stage
    isosurface_resolution: 128 # consistent with last stage
    isosurface_deformable_grid: true
    isosurface_remove_outliers: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096
    fix_geometry: true


  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "solid-color-background"
  background:
    n_output_dims: 3
#    color: [1.0, 1.0, 1.0] # you can set the background as whole white, and you need add the "white background" to prompt
    color: [0.58, 0.47, 0.41] # magic background

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: gl

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "/nas6/hongyuliu/stable-diffusion-2-1-base"
    prompt: ???
#    sup_prompt: ', flawless face'
##    , sketch, cartoon, drawing you need delete these three neg prompt when generate unreal-domain head (i.e, a head of Saber in FateStayNight)
    negative_prompt: 'worst quality, low quality, overexposed, underexposed, semi-realistic, over saturation, sketch, cartoon, drawing'
  landmark_dir: 'load/headartist/tmp.png'
  guidance_type: "ssd-head-guidance"
  guidance:
    pretrained_model_name_or_path: "/nas6/hongyuliu/stable-diffusion-2-1-base"
    controlnet_name_or_path: "/home/liuhongyu/code/ControlNetMediaPipeFace"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: [10000, 0.98, 0.7, 10001] # annealed to 0.5 after 5000 steps,0.7
    condition_scale: 1.



  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_ssd: 1.
    lambda_perceptual: 100.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001
      guidance:
        lr: 0.0001

trainer:
  max_steps: 2070
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed


checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
